require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe DestinationsController do
   describe "When not logged in" do
     before(:each) do
       @group = FactoryGirl.create :group
       @destination = FactoryGirl.create(:destination, :group => @group)
     end

     it "on the show page should redirect to signin page" do
       get :show, {:group_id => @group.id, :id => @destination.id}
       response.should redirect_to(new_user_session_path)
     end

     it "on the edit page should redirect to signin page" do
       get :edit, {:group_id => @group.id, :id => @destination.id}
       response.should redirect_to(new_user_session_path)
     end

     it "on the index page should redirect to signin page" do
       get :index, {:group_id => @group.id}
       response.should redirect_to(new_user_session_path)
     end

     it "on the new page should redirect to signin page" do
       get :new, {:group_id => @group.id}
       response.should redirect_to(new_user_session_path)
     end

   end

   describe "responses" do
     before(:each) do
       @current_user = login
       @group = FactoryGirl.create(:group,:user=>controller.current_user)
       @destination = FactoryGirl.create(:destination, :group=>@group)
     end

     it "when requested in CSV format, should not fail" do
       get :responses, {:group_id => @group.id, :id => @destination.id, :format => "csv"}
     end
   end
end
