require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe UsersController do
  describe "bulk_create" do
    pending "it should accept an uploaded file" do
    end
    pending "it should accept an uploaded list of email addesses" do
    end
  end
end
